# This is a basic workflow to help you get started with Actions

name: obo-file-validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'PSI-MOD.obo'

  pull_request:
    branches: [ master, main ]
    paths:
      - 'PSI-MOD.obo'

permissions: 
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v6

    # Runs a single command using the runners shell
    - name: Validate OBO file
      run: ./.github/binaries/psi-obo-helper fix PSI-MOD.obo

    - name: Check for Changes
      id: check_changes
      run: echo "has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

    - name: Push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --global user.name 'OboRobo'
        git config --global user.email 'oborobo@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
        git commit -am "Automated fixes"
        git push
